<a href="https://colab.research.google.com/github/pqiu/BMED3201/blob/main/python_basics/topic_02_strings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# strings

In [1]:
a = 'abcdefg'
print(a)
print(type(a))

abcdefg
<class 'str'>


# Conver one character into integer

In [2]:
ord('B')

66

# Conver one integer to character

In [3]:
# convert on integer to character
chr(66)

'B'

# Three special chr useful in tab delimit files (csv, tsv, txt, ...)

In [4]:
chr(9)

'\t'

In [5]:
chr(10)

'\n'

In [6]:
chr(13)

'\r'

# compute the length of a string: len()

In [7]:
print('String stored in variable a: ', end='') #
print(a)
print(f'String stored in variable a: {a:s}')

print('The length of the string is: ', end='') #
print(len(a))
print(f'The length of the string is: {len(a):d}')


String stored in variable a: abcdefg
String stored in variable a: abcdefg
The length of the string is: 7
The length of the string is: 7


# len() can be applied to list, dict, tuple

In [8]:
# len() can also compute the len of a list, dict, or tuple
s1 = [1, 'a', 90]
print(s1)
print(type(s1))
print(len(s1))
print()

s2 = {'x':1, 'y':'dd', 'z':1.1}
print(s2)
print(type(s2))
print(len(s2))
print()

s3 = 1, 'a', 90
print(s3)
print(type(s3))
print(len(s3))
print()

[1, 'a', 90]
<class 'list'>
3

{'x': 1, 'y': 'dd', 'z': 1.1}
<class 'dict'>
3

(1, 'a', 90)
<class 'tuple'>
3



# len() can be applied to numpy array

In [9]:
import numpy as np

X1 = np.array([1,2,3,4,5])
print(X1)
print(type(X1))
print(len(X1))
print(X1.shape)
print()

X2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(X2)
print(type(X2))
print(len(X2))
print(X2.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
5
(5,)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2
(2, 5)


# string: formatting using %
- %d for int
- %f for float
- %s for str
- %x for hex

In [10]:
# formatting of float numbers
print('%d' % 1.6294)
print('%3d' % 1.6294)
print('%03d' % 1.6294)
print('%f' % 1.6294)
print('%.2f' % 1.6294)
print('%6.2f' % 1.6294)
print('%06.2f' % 1.6294)
print('%.f' % 1.6294)
print('%s' % 1.6294)


1
  1
001
1.629400
1.63
  1.63
001.63
2
1.6294


In [11]:
print('%d, %f, %06.2f, %s, %x' % (1.6, 1.1234567, 1.1, 'abc', 170))

1, 1.123457, 001.10, abc, aa


# string: formatting using format()
Inside the string to be formatted, {0}, {1} ... can be used to indicate where to insert the parameters in format()

In [12]:
'Hello, {0:s} is a string whose length is {1:03d}'.format('abc', len('abc'))

'Hello, abc is a string whose length is 003'

In [13]:
'The last parameter in format() is {2}, and the first parameter is {0}. They do not have to appear in the same order'.format(1,2,3)

'The last parameter in format() is 3, and the first parameter is 1. They do not have to appear in the same order'

In [14]:
'One parameter {1} can be called multiple times, such as {1}. It\' okay if some parameters are not called'.format(1,2,3)

"One parameter 2 can be called multiple times, such as 2. It' okay if some parameters are not called"

# string: formatting using f-string
Anything inside {} is interpreted, and replaced by the interpreted value

In [15]:
r = 2.5
s = 3.14 * r ** 2
print(f'The area of a circle with \nradius {r} is {s:.2f}')

The area of a circle with 
radius 2.5 is 19.62


# string: formatting using r-string
Nothing is interpreted

In [16]:
r = 2.5
s = 3.14 * r ** 2
print(r'The area of a circle with \nradius {r} is {s:.2f}')

The area of a circle with \nradius {r} is {s:.2f}


# Methods of string operations


In [17]:
# concatenation of two strings
s = 'abc' + 'DEF' + 'abc'
print(s)

# turn string into upper case, lower case, or first letter upper case
print( s.upper() )
print( s.lower() )
print( s.capitalize() )

abcDEFabc
ABCDEFABC
abcdefabc
Abcdefabc


In [18]:
s = 'abc' + 'DEF' + 'abc'
print( s.count('ab') )
print( s.startswith('ab') )
print( s.endswith('abc') )
print( s.find('abc') )
print( s.find('abc', s.find('abc')+1) )
print( s.rfind('abc') )
print( s.replace('abc','-') )
print( s.split('bc') )
print( s.strip('bc') )



2
True
True
0
6
6
-DEF-
['a', 'DEFa', '']
abcDEFa


# convert between string and list

In [19]:
s=' '
print(s.join(['xyz','opq','rst']))

xyz opq rst


In [20]:
# convert list into string
l = ['h','e','l','l','o']
print(''.join(l))
print(' '.join(l))
print('-'.join(l))


# conver string to list, where each letter in string is an element of the list
s = "hello"
print( list(s) )
print( [i for i in s] )
print( [s[i] for i in range(len(s))] )


# convert string to list with a defined separator
s = "he--ll--oo--"
print(s.split('--'))
print(s.split('-'))
print(s.split('---'))


hello
h e l l o
h-e-l-l-o
['h', 'e', 'l', 'l', 'o']
['h', 'e', 'l', 'l', 'o']
['h', 'e', 'l', 'l', 'o']
['he', 'll', 'oo', '']
['he', '', 'll', '', 'oo', '', '']
['he--ll--oo--']


# A good reference website
https://www.w3schools.com/python/python_ref_string.asp